version: 1fdfdfd
jobs:fdsfsdf
  build:
    image: node
    script:
    - npm i
    - npm run build
  test:
    image: node
    script:
    - npm i
    - npm run test

stages:
  - build_and_test:
      jobs:
        - build
        - test
